export const project = {
  name: "club-athletic",
  environment: "mgmt",
  managementAccount: "366394957699",
  region: "us-east-1",
  domain: "xn--tshi-l3a.com",
  hostedZoneId: "Z04794863W4QH5DDAT4AZ",
  certificate: {
    certificateArn: {
      mgmt: "arn:aws:acm:us-east-1:366394957699:certificate/90ec2073-35b8-4569-91f8-5db8c1fe1af2",
    },
  },
  vpcId: "vpc-01386cc23ddfbbb97",
  clusterName: "club-athletic",
  pipeline: {
    region: "us-east-1",
    connectionArn: "arn:aws:codeconnections:us-east-1:366394957699:connection/a612c7ed-8ea5-4d6c-9306-a0e3d7af6efd",
    githubOwner: "kaisewhite",
    githubRepository: "club-athletic",
    branch: "main",
  },
  service: {
    name: "web",
    resourceName: "club-athletic-web",
    description: "Club Athletic trip hub: React Router SSR app with the trip concierge agent",
    imageTag: "main",
    healthCheck: "/health",
    subdomain: "meribel",
    desiredCount: 1,
    memoryLimitMiB: 1024,
    cpu: 512,
    containerPort: 4173,
    capacityProvider: "FARGATE",
    disableIpv6: true,
    secrets: [
      "ANTHROPIC_API_KEY",
      "DATABASE_URL",
      "DATABASE_URL_POOLED",
      "CLAUDE_MANAGED_ENVIRONMENT_ID",
      "CLAUDE_TRIP_AGENT_ID",
      "CLAUDE_TRIP_MEMORY_STORE_ID",
    ],
  },
} as const;
