-- Generated by installed Prisma 7.8 migrate diff from the baseline schema.
-- Augmented with deterministic legacy-message backfill and Q6 FK deferral.
-- Capability provisioning is separate: prisma/chat-grants.sql (administrator only).
BEGIN;

-- AlterTable
ALTER TABLE "Upload" ADD COLUMN     "mountPath" TEXT,
ADD COLUMN     "mountedFileDeletedAt" TIMESTAMPTZ(3),
ADD COLUMN     "mountedFileId" TEXT,
ADD COLUMN     "originalFileDeletedAt" TIMESTAMPTZ(3),
ADD COLUMN     "sessionResourceDeletedAt" TIMESTAMPTZ(3),
ADD COLUMN     "sessionResourceId" TEXT,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'pending',
ALTER COLUMN "fileId" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Conversation" ADD COLUMN     "activeRequestId" TEXT,
ADD COLUMN     "activeTurnId" TEXT,
ADD COLUMN     "error" TEXT,
ADD COLUMN     "finishedAt" TIMESTAMPTZ(3),
ADD COLUMN     "nextEventSeq" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "requestId" TEXT,
ADD COLUMN     "runtimeStatus" TEXT,
ADD COLUMN     "status" TEXT NOT NULL DEFAULT 'running',
ADD COLUMN     "streamIndex" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "Message" ADD COLUMN     "lifecycleAppliedAt" TIMESTAMPTZ(3),
ADD COLUMN     "payload" JSONB,
ADD COLUMN     "providerEventKey" TEXT,
ADD COLUMN     "requestId" TEXT,
ADD COLUMN     "seq" INTEGER,
ADD COLUMN     "type" TEXT;

-- AlterTable
ALTER TABLE "PendingExtraction" ADD COLUMN     "claimedFirstName" TEXT,
ADD COLUMN     "claimedLastName" TEXT,
ADD COLUMN     "committedFlightIds" JSONB,
ADD COLUMN     "confirmationMessageId" TEXT,
ADD COLUMN     "confirmedAt" TIMESTAMPTZ(3),
ADD COLUMN     "consumedAt" TIMESTAMPTZ(3),
ADD COLUMN     "createdGuestId" TEXT,
ADD COLUMN     "guestCreationConsentMessageId" TEXT,
ADD COLUMN     "guestId" TEXT,
ADD COLUMN     "nameMessageId" TEXT,
ADD COLUMN     "phase" TEXT NOT NULL DEFAULT 'collecting',
ADD COLUMN     "readbackMessageId" TEXT,
ADD COLUMN     "readbackVersion" INTEGER,
ADD COLUMN     "toolCallId" TEXT,
ADD COLUMN     "uploadId" TEXT,
ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 1;

-- Preserve legacy transcript rows and derive their event representation once.
-- createdAt ties are resolved by id, independently within each conversation.
WITH ordered AS (
    SELECT "id", (row_number() OVER (
        PARTITION BY "conversationId" ORDER BY "createdAt", "id"
    ) - 1)::INTEGER AS seq
    FROM "Message"
)
UPDATE "Message" AS message
SET "seq" = ordered.seq,
    "type" = CASE message."role"
        WHEN 'user' THEN 'user_message'
        WHEN 'assistant' THEN 'message'
        WHEN 'tool' THEN 'tool_result'
        ELSE 'system'
    END,
    "payload" = jsonb_strip_nulls(jsonb_build_object(
        'text', message."content",
        'role', message."role",
        'sourceSections', message."sourceSections",
        'uploadId', message."uploadId"
    ))
FROM ordered WHERE message."id" = ordered."id";

ALTER TABLE "Message"
    ALTER COLUMN "seq" SET NOT NULL,
    ALTER COLUMN "type" SET NOT NULL,
    ALTER COLUMN "payload" SET NOT NULL;

UPDATE "Conversation" AS conversation
SET "nextEventSeq" = events.next_seq
FROM (
    SELECT "conversationId", max("seq") + 1 AS next_seq
    FROM "Message" GROUP BY "conversationId"
) AS events
WHERE conversation."id" = events."conversationId";

-- Existing original file IDs are uploads, not pending reservations. Do not infer
-- mounted resource identities or successful deletion of unrecorded copies.
UPDATE "Upload"
SET "status" = CASE WHEN "deletedFromAnthropicAt" IS NOT NULL THEN 'deleted' ELSE 'uploaded' END,
    "originalFileDeletedAt" = "deletedFromAnthropicAt"
WHERE "fileId" IS NOT NULL;

-- CreateIndex
CREATE UNIQUE INDEX "Conversation_requestId_key" ON "Conversation"("requestId");

-- CreateIndex
CREATE UNIQUE INDEX "Message_conversationId_seq_key" ON "Message"("conversationId", "seq");

-- CreateIndex
CREATE UNIQUE INDEX "Message_conversationId_providerEventKey_key" ON "Message"("conversationId", "providerEventKey");

-- CreateIndex
CREATE UNIQUE INDEX "Message_conversationId_requestId_key" ON "Message"("conversationId", "requestId");

-- CreateIndex
CREATE INDEX "PendingExtraction_uploadId_idx" ON "PendingExtraction"("uploadId");

-- CreateIndex
CREATE INDEX "PendingExtraction_guestId_idx" ON "PendingExtraction"("guestId");

-- CreateIndex
CREATE INDEX "PendingExtraction_createdGuestId_idx" ON "PendingExtraction"("createdGuestId");

-- CreateIndex
CREATE INDEX "PendingExtraction_nameMessageId_idx" ON "PendingExtraction"("nameMessageId");

-- CreateIndex
CREATE INDEX "PendingExtraction_readbackMessageId_idx" ON "PendingExtraction"("readbackMessageId");

-- CreateIndex
CREATE INDEX "PendingExtraction_confirmationMessageId_idx" ON "PendingExtraction"("confirmationMessageId");

-- CreateIndex
CREATE INDEX "PendingExtraction_guestCreationConsentMessageId_idx" ON "PendingExtraction"("guestCreationConsentMessageId");

-- CreateIndex
CREATE UNIQUE INDEX "PendingExtraction_conversationId_toolCallId_key" ON "PendingExtraction"("conversationId", "toolCallId");

-- AddForeignKey
ALTER TABLE "PendingExtraction" ADD CONSTRAINT "PendingExtraction_uploadId_fkey" FOREIGN KEY ("uploadId") REFERENCES "Upload"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PendingExtraction" ADD CONSTRAINT "PendingExtraction_guestId_fkey" FOREIGN KEY ("guestId") REFERENCES "Guest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PendingExtraction" ADD CONSTRAINT "PendingExtraction_createdGuestId_fkey" FOREIGN KEY ("createdGuestId") REFERENCES "Guest"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PendingExtraction" ADD CONSTRAINT "PendingExtraction_nameMessageId_fkey" FOREIGN KEY ("nameMessageId") REFERENCES "Message"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PendingExtraction" ADD CONSTRAINT "PendingExtraction_readbackMessageId_fkey" FOREIGN KEY ("readbackMessageId") REFERENCES "Message"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PendingExtraction" ADD CONSTRAINT "PendingExtraction_confirmationMessageId_fkey" FOREIGN KEY ("confirmationMessageId") REFERENCES "Message"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PendingExtraction" ADD CONSTRAINT "PendingExtraction_guestCreationConsentMessageId_fkey" FOREIGN KEY ("guestCreationConsentMessageId") REFERENCES "Message"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- Preserve the live-flight unique index. A replacement transaction first points
-- the old row at a preallocated ID, then inserts that replacement before commit.
ALTER TABLE "Flight" ALTER CONSTRAINT "Flight_supersededById_fkey"
    DEFERRABLE INITIALLY DEFERRED;

COMMIT;
